//ADDRESSES
export const LOAD_ADDRESSES_SUCCESS = "LOAD_ADDRESSES_SUCCESS";
export const LOAD_ADDRESSES_FAILURE = "LOAD_ADDRESSES_FAILURE";
export const LOAD_ADDRESSES_PENDING = "LOAD_ADDRESSES_PENDING";

export const LOAD_ADDRESS_SUCCESS = "LOAD_ADDRESS_SUCCESS";
export const LOAD_ADDRESS_FAILURE = "LOAD_ADDRESS_FAILURE";
export const LOAD_ADDRESS_PENDING = "LOAD_ADDRESS_PENDING";

//PENDING
export const LOAD_PENDINGS_SUCCESS = "LOAD_PENDINGS_SUCCESS";
export const LOAD_PENDINGS_FAILURE = "LOAD_PENDINGS_FAILURE";
export const LOAD_PENDINGS_PENDING = "LOAD_PENDINGS_PENDING";

export const LOAD_PENDING_SUCCESS = "LOAD_PENDING_SUCCESS";
export const LOAD_PENDING_FAILURE = "LOAD_PENDING_FAILURE";
export const LOAD_PENDING_PENDING = "LOAD_PENDING_PENDING";

export const ADD_PENDING_SUCCESS = "ADD_PENDING_SUCCESS";
export const ADD_PENDING_FAILURE = "ADD_PENDING_FAILURE";
export const ADD_PENDING_PENDING = "ADD_PENDING_PENDING";

export const DELETE_PENDING_SUCCESS = "DELETE_PENDING_SUCCESS";
export const DELETE_PENDING_FAILURE = "DELETE_PENDING_FAILURE";
export const DELETE_PENDING_PENDING = "DELETE_PENDING_PENDING";

export const EDIT_PENDING_SUCCESS = "EDIT_PENDING_SUCCESS";
export const EDIT_PENDING_FAILURE = "EDIT_PENDING_FAILURE";
export const EDIT_PENDING_PENDING = "EDIT_PENDING_PENDING";

//ARCHIVED
export const LOAD_ARCHIVES_SUCCESS = "LOAD_ARCHIVES_SUCCESS";
export const LOAD_ARCHIVES_FAILURE = "LOAD_ARCHIVES_FAILURE";
export const LOAD_ARCHIVES_PENDING = "LOAD_ARCHIVES_PENDING";

export const LOAD_ARCHIVE_SUCCESS = "LOAD_ARCHIVE_SUCCESS";
export const LOAD_ARCHIVE_FAILURE = "LOAD_ARCHIVE_FAILURE";
export const LOAD_ARCHIVE_PENDING = "LOAD_ARCHIVE_PENDING";

export const ADD_ARCHIVE_SUCCESS = "ADD_ARCHIVE_SUCCESS";
export const ADD_ARCHIVE_FAILURE = "ADD_ARCHIVE_FAILURE";
export const ADD_ARCHIVE_PENDING = "ADD_ARCHIVE_PENDING";

export const DELETE_ARCHIVE_SUCCESS = "DELETE_ARCHIVE_SUCCESS";
export const DELETE_ARCHIVE_FAILURE = "DELETE_ARCHIVE_FAILURE";
export const DELETE_ARCHIVE_PENDING = "DELETE_ARCHIVE_PENDING";

export const EDIT_ARCHIVE_SUCCESS = "EDIT_ARCHIVE_SUCCESS";
export const EDIT_ARCHIVE_FAILURE = "EDIT_ARCHIVE_FAILURE";
export const EDIT_ARCHIVE_PENDING = "EDIT_ARCHIVE_PENDING";

//UWREVIEWS
export const LOAD_UWREVIEWS_SUCCESS = "LOAD_UWREVIEWS_SUCCESS";
export const LOAD_UWREVIEWS_FAILURE = "LOAD_UWREVIEWS_FAILURE";
export const LOAD_UWREVIEWS_PENDING = "LOAD_UWREVIEWS_PENDING";

export const LOAD_UWREVIEW_SUCCESS = "LOAD_UWREVIEW_SUCCESS";
export const LOAD_UWREVIEW_FAILURE = "LOAD_UWREVIEW_FAILURE";
export const LOAD_UWREVIEW_PENDING = "LOAD_UWREVIEW_PENDING";

export const ADD_UWREVIEW_SUCCESS = "ADD_UWREVIEW_SUCCESS";
export const ADD_UWREVIEW_FAILURE = "ADD_UWREVIEW_FAILURE";
export const ADD_UWREVIEW_PENDING = "ADD_UWREVIEW_PENDING";

export const DELETE_UWREVIEW_SUCCESS = "DELETE_UWREVIEW_SUCCESS";
export const DELETE_UWREVIEW_FAILURE = "DELETE_UWREVIEW_FAILURE";
export const DELETE_UWREVIEW_PENDING = "DELETE_UWREVIEW_PENDING";

export const EDIT_UWREVIEW_SUCCESS = "EDIT_UWREVIEW_SUCCESS";
export const EDIT_UWREVIEW_FAILURE = "EDIT_UWREVIEW_FAILURE";
export const EDIT_UWREVIEW_PENDING = "EDIT_UWREVIEW_PENDING";

//Nav search bar
export const SEARCH_FROM_NAV = "SEARCH_FROM_NAV";
